services:
  - type: web
    name: magis-studio-api
    env: node
    rootDir: backend # <--- Importante: le dice a Render dónde está el código
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - fromGroup: magis-secrets # Usaremos un grupo para las llaves
